# Generated by Django 6.1.1 on 2026-10-05 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('convertido', 'Convertido en orden')], default='abierto', max_length=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='cuentas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.carrito')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=12)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='cuentas.cliente')),
            ],
            options={
                'verbose_name_plural': 'órdenes',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(max_length=120)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.lugar')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.orden')),
            ],
            options={
                'verbose_name': 'item de orden',
                'verbose_name_plural': 'items de orden',
            },
        ),
        migrations.AddConstraint(
            model_name='carrito',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierto')), fields=('cliente',), name='un_carrito_abierto_por_cliente'),
        ),
        migrations.AddConstraint(
            model_name='itemcarrito',
            constraint=models.UniqueConstraint(fields=('carrito', 'lugar'), name='un_item_por_lugar_en_carrito'),
        ),
        migrations.AddConstraint(
            model_name='itemcarrito',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 1)), name='item_carrito_cantidad_minima'),
        ),
    ]
